/** Generated by YAKINDU Statechart Tools code generator. */


#include "../src/sc_types.h"

#include "macchina_stati.h"

/*! \file Implementation of the state machine 'macchina_stati'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_StateB(Macchina_stati* handle);
static void enseq_main_region_StateA_default(Macchina_stati* handle);
static void enseq_main_region_StateB_default(Macchina_stati* handle);
static void enseq_main_region_default(Macchina_stati* handle);
static void exseq_main_region_StateA(Macchina_stati* handle);
static void exseq_main_region_StateB(Macchina_stati* handle);
static void exseq_main_region(Macchina_stati* handle);
static void react_main_region__entry_Default(Macchina_stati* handle);

/*! State machine reactions. */
static sc_boolean react(Macchina_stati* handle);

/*! The reactions of state StateA. */
static sc_boolean main_region_StateA_react(Macchina_stati* handle, const sc_boolean try_transition);

/*! The reactions of state StateB. */
static sc_boolean main_region_StateB_react(Macchina_stati* handle, const sc_boolean try_transition);


static void clearInEvents(Macchina_stati* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Macchina_stati* handle);



static void macchina_stati_eventqueue_init(macchina_stati_eventqueue * eq, macchina_stati_event *buffer, sc_integer capacity);
static sc_integer macchina_stati_eventqueue_size(macchina_stati_eventqueue * eq);
static void macchina_stati_event_init(macchina_stati_event * ev, Macchina_statiEventID name);
static macchina_stati_event macchina_stati_eventqueue_pop(macchina_stati_eventqueue * eq);
static sc_boolean macchina_stati_eventqueue_push(macchina_stati_eventqueue * eq, macchina_stati_event ev);
static void macchina_stati_add_event_to_queue(macchina_stati_eventqueue * eq, Macchina_statiEventID name);
static void macchina_stati_dispatch_event(Macchina_stati* handle, const macchina_stati_event * event);
static macchina_stati_event macchina_stati_get_next_event(Macchina_stati* handle);
static void macchina_stati_dispatch_next_event(Macchina_stati* handle);


void macchina_stati_init(Macchina_stati* handle)
{
	sc_integer i;
	
	for (i = 0; i < MACCHINA_STATI_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Macchina_stati_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	
	
	
	handle->isExecuting = bool_false;
	macchina_stati_eventqueue_init(&handle->in_event_queue, handle->in_buffer, MACCHINA_STATI_IN_EVENTQUEUE_BUFFERSIZE);
}

void macchina_stati_enter(Macchina_stati* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart macchina_stati */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void macchina_stati_exit(Macchina_stati* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart macchina_stati */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}


sc_boolean macchina_stati_is_active(const Macchina_stati* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < MACCHINA_STATI_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Macchina_stati_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean macchina_stati_is_final(const Macchina_stati* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean macchina_stati_is_state_active(const Macchina_stati* handle, Macchina_statiStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Macchina_stati_main_region_StateA :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MACCHINA_STATI_MAIN_REGION_STATEA] == Macchina_stati_main_region_StateA
			);
			break;
		case Macchina_stati_main_region_StateB :
			result = (sc_boolean) (handle->stateConfVector[SCVI_MACCHINA_STATI_MAIN_REGION_STATEB] == Macchina_stati_main_region_StateB
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Macchina_stati* handle)
{
	handle->iface.myEvent_raised = bool_false;
}

static void run_cycle(Macchina_stati* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	macchina_stati_dispatch_next_event(handle);
	do
	{ 
		for (handle->stateConfVectorPosition = 0;
			handle->stateConfVectorPosition < MACCHINA_STATI_MAX_ORTHOGONAL_STATES;
			handle->stateConfVectorPosition++)
			{
				
			switch (handle->stateConfVector[handle->stateConfVectorPosition])
			{
			case Macchina_stati_main_region_StateA:
			{
				main_region_StateA_react(handle, bool_true);
				break;
			}
			case Macchina_stati_main_region_StateB:
			{
				main_region_StateB_react(handle, bool_true);
				break;
			}
			default:
				break;
			}
		}
		clearInEvents(handle);
		macchina_stati_dispatch_next_event(handle);
	} while (handle->iface.myEvent_raised == bool_true);
	handle->isExecuting = bool_false;
}


void macchina_stati_raise_myEvent(Macchina_stati* handle)
{
	macchina_stati_add_event_to_queue(&(handle->in_event_queue), Macchina_stati_myEvent);
	run_cycle(handle);
}



void* macchina_stati_get_state(const Macchina_stati* handle)
{
	return handle->iface.state;
}
void macchina_stati_set_state(Macchina_stati* handle, void* value)
{
	handle->iface.state = value;
}

/* implementations of all internal functions */

/* Entry action for state 'StateB'. */
static void enact_main_region_StateB(Macchina_stati* handle)
{
	SC_UNUSED(handle);
	/* Entry action for state 'StateB'. */
	funzione_stampa(127);
}

/* 'default' enter sequence for state StateA */
static void enseq_main_region_StateA_default(Macchina_stati* handle)
{
	/* 'default' enter sequence for state StateA */
	handle->stateConfVector[0] = Macchina_stati_main_region_StateA;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state StateB */
static void enseq_main_region_StateB_default(Macchina_stati* handle)
{
	/* 'default' enter sequence for state StateB */
	enact_main_region_StateB(handle);
	handle->stateConfVector[0] = Macchina_stati_main_region_StateB;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Macchina_stati* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state StateA */
static void exseq_main_region_StateA(Macchina_stati* handle)
{
	/* Default exit sequence for state StateA */
	handle->stateConfVector[0] = Macchina_stati_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state StateB */
static void exseq_main_region_StateB(Macchina_stati* handle)
{
	/* Default exit sequence for state StateB */
	handle->stateConfVector[0] = Macchina_stati_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Macchina_stati* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of macchina_stati.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Macchina_stati_main_region_StateA :
		{
			exseq_main_region_StateA(handle);
			break;
		}
		case Macchina_stati_main_region_StateB :
		{
			exseq_main_region_StateB(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Macchina_stati* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_StateA_default(handle);
}


static sc_boolean react(Macchina_stati* handle)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return bool_false;
}

static sc_boolean main_region_StateA_react(Macchina_stati* handle, const sc_boolean try_transition)
{
	/* The reactions of state StateA. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.myEvent_raised == bool_true)
			{ 
				exseq_main_region_StateA(handle);
				enseq_main_region_StateB_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}

static sc_boolean main_region_StateB_react(Macchina_stati* handle, const sc_boolean try_transition)
{
	/* The reactions of state StateB. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.myEvent_raised == bool_true)
			{ 
				exseq_main_region_StateB(handle);
				enseq_main_region_StateA_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}




static void macchina_stati_eventqueue_init(macchina_stati_eventqueue * eq, macchina_stati_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer macchina_stati_eventqueue_size(macchina_stati_eventqueue * eq)
{
	return eq->size;
}

static macchina_stati_event macchina_stati_eventqueue_pop(macchina_stati_eventqueue * eq)
{
	macchina_stati_event event;
	if(macchina_stati_eventqueue_size(eq) <= 0) {
		macchina_stati_event_init(&event, Macchina_stati_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean macchina_stati_eventqueue_push(macchina_stati_eventqueue * eq, macchina_stati_event ev)
{
	if(macchina_stati_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void macchina_stati_event_init(macchina_stati_event * ev, Macchina_statiEventID name)
{
	ev->name = name;
}

static void macchina_stati_add_event_to_queue(macchina_stati_eventqueue * eq, Macchina_statiEventID name)
{
	macchina_stati_event event;
	macchina_stati_event_init(&event, name);
	macchina_stati_eventqueue_push(eq, event);
}

static void macchina_stati_dispatch_event(Macchina_stati* handle, const macchina_stati_event * event) {
	switch(event->name) {
		case Macchina_stati_myEvent:
		{
			handle->iface.myEvent_raised = bool_true;
			break;
		}
		default:
			break;
	}
}

static macchina_stati_event macchina_stati_get_next_event(Macchina_stati* handle)
{
	macchina_stati_event next_event;
	macchina_stati_event_init(&next_event, Macchina_stati_invalid_event);
	if(macchina_stati_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = macchina_stati_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static void macchina_stati_dispatch_next_event(Macchina_stati* handle)
{
	macchina_stati_event nextEvent;
	nextEvent = macchina_stati_get_next_event(handle);
	macchina_stati_dispatch_event(handle, &nextEvent);
}
