/** Generated by YAKINDU Statechart Tools code generator. */


#include "../src/sc_types.h"

#include "Nomemio.h"

/*! \file Implementation of the state machine 'Nomemio'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enseq_main_region_StateA_default(Nomemio* handle);
static void enseq_main_region_StateB_default(Nomemio* handle);
static void enseq_main_region_default(Nomemio* handle);
static void exseq_main_region_StateA(Nomemio* handle);
static void exseq_main_region_StateB(Nomemio* handle);
static void exseq_main_region(Nomemio* handle);
static void react_main_region__entry_Default(Nomemio* handle);

/*! State machine reactions. */
static sc_boolean react(Nomemio* handle);

/*! The reactions of state StateA. */
static sc_boolean main_region_StateA_react(Nomemio* handle, const sc_boolean try_transition);

/*! The reactions of state StateB. */
static sc_boolean main_region_StateB_react(Nomemio* handle, const sc_boolean try_transition);


static void clearInEvents(Nomemio* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Nomemio* handle);



static void nomemio_eventqueue_init(nomemio_eventqueue * eq, nomemio_event *buffer, sc_integer capacity);
static sc_integer nomemio_eventqueue_size(nomemio_eventqueue * eq);
static void nomemio_event_init(nomemio_event * ev, NomemioEventID name);
static nomemio_event nomemio_eventqueue_pop(nomemio_eventqueue * eq);
static sc_boolean nomemio_eventqueue_push(nomemio_eventqueue * eq, nomemio_event ev);
static void nomemio_add_event_to_queue(nomemio_eventqueue * eq, NomemioEventID name);
static void nomemio_dispatch_event(Nomemio* handle, const nomemio_event * event);
static nomemio_event nomemio_get_next_event(Nomemio* handle);
static void nomemio_dispatch_next_event(Nomemio* handle);


void nomemio_init(Nomemio* handle)
{
	sc_integer i;
	
	for (i = 0; i < NOMEMIO_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Nomemio_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	
	
	
	handle->isExecuting = bool_false;
	nomemio_eventqueue_init(&handle->in_event_queue, handle->in_buffer, NOMEMIO_IN_EVENTQUEUE_BUFFERSIZE);
}

void nomemio_enter(Nomemio* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Nomemio */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void nomemio_exit(Nomemio* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Nomemio */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}


sc_boolean nomemio_is_active(const Nomemio* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < NOMEMIO_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Nomemio_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean nomemio_is_final(const Nomemio* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean nomemio_is_state_active(const Nomemio* handle, NomemioStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Nomemio_main_region_StateA :
			result = (sc_boolean) (handle->stateConfVector[SCVI_NOMEMIO_MAIN_REGION_STATEA] == Nomemio_main_region_StateA
			);
			break;
		case Nomemio_main_region_StateB :
			result = (sc_boolean) (handle->stateConfVector[SCVI_NOMEMIO_MAIN_REGION_STATEB] == Nomemio_main_region_StateB
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Nomemio* handle)
{
	handle->iface.myEvent_raised = bool_false;
}

static void run_cycle(Nomemio* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	nomemio_dispatch_next_event(handle);
	do
	{ 
		for (handle->stateConfVectorPosition = 0;
			handle->stateConfVectorPosition < NOMEMIO_MAX_ORTHOGONAL_STATES;
			handle->stateConfVectorPosition++)
			{
				
			switch (handle->stateConfVector[handle->stateConfVectorPosition])
			{
			case Nomemio_main_region_StateA:
			{
				main_region_StateA_react(handle, bool_true);
				break;
			}
			case Nomemio_main_region_StateB:
			{
				main_region_StateB_react(handle, bool_true);
				break;
			}
			default:
				break;
			}
		}
		clearInEvents(handle);
		nomemio_dispatch_next_event(handle);
	} while (handle->iface.myEvent_raised == bool_true);
	handle->isExecuting = bool_false;
}


void nomemio_raise_myEvent(Nomemio* handle)
{
	nomemio_add_event_to_queue(&(handle->in_event_queue), Nomemio_myEvent);
	run_cycle(handle);
}




/* implementations of all internal functions */

/* 'default' enter sequence for state StateA */
static void enseq_main_region_StateA_default(Nomemio* handle)
{
	/* 'default' enter sequence for state StateA */
	handle->stateConfVector[0] = Nomemio_main_region_StateA;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state StateB */
static void enseq_main_region_StateB_default(Nomemio* handle)
{
	/* 'default' enter sequence for state StateB */
	handle->stateConfVector[0] = Nomemio_main_region_StateB;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Nomemio* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state StateA */
static void exseq_main_region_StateA(Nomemio* handle)
{
	/* Default exit sequence for state StateA */
	handle->stateConfVector[0] = Nomemio_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state StateB */
static void exseq_main_region_StateB(Nomemio* handle)
{
	/* Default exit sequence for state StateB */
	handle->stateConfVector[0] = Nomemio_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Nomemio* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Nomemio.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Nomemio_main_region_StateA :
		{
			exseq_main_region_StateA(handle);
			break;
		}
		case Nomemio_main_region_StateB :
		{
			exseq_main_region_StateB(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Nomemio* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_StateA_default(handle);
}


static sc_boolean react(Nomemio* handle)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return bool_false;
}

static sc_boolean main_region_StateA_react(Nomemio* handle, const sc_boolean try_transition)
{
	/* The reactions of state StateA. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.myEvent_raised == bool_true)
			{ 
				exseq_main_region_StateA(handle);
				enseq_main_region_StateB_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}

static sc_boolean main_region_StateB_react(Nomemio* handle, const sc_boolean try_transition)
{
	/* The reactions of state StateB. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.myEvent_raised == bool_true)
			{ 
				exseq_main_region_StateB(handle);
				enseq_main_region_StateA_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}




static void nomemio_eventqueue_init(nomemio_eventqueue * eq, nomemio_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer nomemio_eventqueue_size(nomemio_eventqueue * eq)
{
	return eq->size;
}

static nomemio_event nomemio_eventqueue_pop(nomemio_eventqueue * eq)
{
	nomemio_event event;
	if(nomemio_eventqueue_size(eq) <= 0) {
		nomemio_event_init(&event, Nomemio_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean nomemio_eventqueue_push(nomemio_eventqueue * eq, nomemio_event ev)
{
	if(nomemio_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void nomemio_event_init(nomemio_event * ev, NomemioEventID name)
{
	ev->name = name;
}

static void nomemio_add_event_to_queue(nomemio_eventqueue * eq, NomemioEventID name)
{
	nomemio_event event;
	nomemio_event_init(&event, name);
	nomemio_eventqueue_push(eq, event);
}

static void nomemio_dispatch_event(Nomemio* handle, const nomemio_event * event) {
	switch(event->name) {
		case Nomemio_myEvent:
		{
			handle->iface.myEvent_raised = bool_true;
			break;
		}
		default:
			break;
	}
}

static nomemio_event nomemio_get_next_event(Nomemio* handle)
{
	nomemio_event next_event;
	nomemio_event_init(&next_event, Nomemio_invalid_event);
	if(nomemio_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = nomemio_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static void nomemio_dispatch_next_event(Nomemio* handle)
{
	nomemio_event nextEvent;
	nextEvent = nomemio_get_next_event(handle);
	nomemio_dispatch_event(handle, &nextEvent);
}
